config/routes.rb
Fordecise::Application.routes.draw do
  

  resources :gallery_attachments

  resources :galleries

  resources :posts

  get "/" => "home#index", :as => "root"
  get '/contact'=>"home#contact",:as=>"contact"
  devise_for :users
  

end

app/models/gallery_attachment.rb
class GalleryAttachment < ActiveRecord::Base
   mount_uploader :photos, PhotosUploader
   belongs_to :gallery
end

app/controllers/gallery_attachments_controller.rb
class GalleryAttachmentsController < ApplicationController
  before_action :set_gallery_attachment, only: [:show, :edit, :update, :destroy]

  # GET /gallery_attachments
  # GET /gallery_attachments.json
  def index
    @gallery_attachments = GalleryAttachment.all
  end

  # GET /gallery_attachments/1
  # GET /gallery_attachments/1.json
  def show
  end

  # GET /gallery_attachments/new
  def new
    @gallery_attachment = GalleryAttachment.new
  end

  # GET /gallery_attachments/1/edit
  def edit
  end

  # POST /gallery_attachments
  # POST /gallery_attachments.json
  def create
    @gallery_attachment = GalleryAttachment.new(gallery_attachment_params)

    respond_to do |format|
      if @gallery_attachment.save
        format.html { redirect_to @gallery_attachment, notice: 'Gallery attachment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gallery_attachment }
      else
        format.html { render action: 'new' }
        format.json { render json: @gallery_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gallery_attachments/1
  # PATCH/PUT /gallery_attachments/1.json
  def update
    respond_to do |format|
      if @gallery_attachment.update(gallery_attachment_params)
        format.html { redirect_to @gallery_attachment, notice: 'Gallery attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gallery_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gallery_attachments/1
  # DELETE /gallery_attachments/1.json
  def destroy
    @gallery_attachment.destroy
    respond_to do |format|
      format.html { redirect_to gallery_attachments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery_attachment
      @gallery_attachment = GalleryAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_attachment_params
      params.require(:gallery_attachment).permit(:gallery_id, :photos)
    end
end

app/helpers/gallery_attachments_helper.rb
module GalleryAttachmentsHelper
end

app/views/gallery_attachments/_form.html.erb
<%= form_for(@gallery_attachment) do |f| %>
  <% if @gallery_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery_attachment.errors.count, "error") %> prohibited this gallery_attachment from being saved:</h2>

      <ul>
      <% @gallery_attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gallery_id %><br>
    <%= f.number_field :gallery_id %>
  </div>
  <div class="field">
    <%= f.label :photos %><br>
    <%= f.text_field :photos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gallery_attachments/edit.html.erb
<h1>Editing gallery_attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery_attachment %> |
<%= link_to 'Back', gallery_attachments_path %>

app/views/gallery_attachments/index.html.erb
<h1>Listing gallery_attachments</h1>

<table>
  <thead>
    <tr>
      <th>Gallery</th>
      <th>Photos</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @gallery_attachments.each do |gallery_attachment| %>
      <tr>
        <td><%= gallery_attachment.gallery_id %></td>
        <td><%= gallery_attachment.photos %></td>
        <td><%= link_to 'Show', gallery_attachment %></td>
        <td><%= link_to 'Edit', edit_gallery_attachment_path(gallery_attachment) %></td>
        <td><%= link_to 'Destroy', gallery_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery attachment', new_gallery_attachment_path %>

app/views/gallery_attachments/new.html.erb
<h1>New gallery_attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', gallery_attachments_path %>

app/views/gallery_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gallery:</strong>
  <%= @gallery_attachment.gallery_id %>
</p>

<p>
  <strong>Photos:</strong>
  <%= @gallery_attachment.photos %>
</p>

<%= link_to 'Edit', edit_gallery_attachment_path(@gallery_attachment) %> |
<%= link_to 'Back', gallery_attachments_path %>