config/routes.rb
Fordecise::Application.routes.draw do
  

  resources :gallery_attachments

  resources :galleries

  resources :posts

  get "/" => "home#index", :as => "root"
  get '/contact'=>"home#contact",:as=>"contact"
  devise_for :users
  

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
   has_many :gallery_attachments
   accepts_nested_attributes_for :gallery_attachments
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @title="GALLERY"
    meta("index","","")
    @galleries = Gallery.all
     @gallery_attachments=GalleryAttachment.all; 
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
     @gallery_attachments=@gallery.gallery_attachments.all;
  end

  # GET /galleries/new
  def new
    if user_signed_in?
      @gallery = Gallery.new
      @gallery_attachment = @gallery.gallery_attachments.build
  else
    redirect_to('/users/sign_in')
    end
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    if user_signed_in?
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        params[:gallery_attachments]['photos'].each do |a|
          @gallery_attachment = @gallery.gallery_attachments.create!(:photos => a, :gallery_id => @gallery.id)
       end
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gallery }
      else
        format.html { render action: 'new' }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
    else
      redirect_to('/users/sign_in')
    end

  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    if user_signed_in?
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  else
    redirect_to('/users/sign_in')
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    if user_signed_in?
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  else
    redirect_to('/users/sign_in')
    end
  end
  def meta(fn_name,cust_title,cust_url)
    if fn_name=="index"
      puts "INDEX"

      $og_title="STUDENTS FM|GALLERY"
      $og_image="/assets/"
    elsif fn_name=="show"
      $og_title=cust_title
      $url=cust_url
    end
    
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:caption)
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.fields_for :gallery_attachment do |p| %>
     <div class="field">
       <%= p.label :photos %><br>
       <%= p.file_field :photos, :multiple => true, name: "gallery_attachments[photos][]" %>
     </div>
   <% end %>
  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<div class="container">
	<% if user_signed_in?%>
	<% @galleries.each do |gallery| %>
	<%= gallery.caption %>
	<%= link_to 'Show', gallery %>
	<%= link_to 'Edit', edit_gallery_path(gallery) %>

	<%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %>
	<%= link_to 'New Gallery', new_gallery_path %>
	<% else %>
	<% @galleries.each do |gallery| %>
	<div class="row">
		<div class="col-md-12">
			<img src='<%=@gallery_attachments[gallery.id].photos%>' width="100" height='100'>
		</div>

		<div class="col-md-1 text-center">
			<p><%= link_to gallery.caption, gallery %></p>
		</div>
	</div>
	<% end %>
	<% end %>
</div>

app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<p><%= @gallery.caption %></p>
<%if user_signed_in?%>
<% @gallery_attachments.each do |p| %>
  <%= image_tag p.photos_url, :size => "150x150" %>
  <%= link_to "Destroy", p, method: :delete %>
<% end %>
<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>
<% else %>
<% @gallery_attachments.each do |p| %>
  <%= image_tag p.photos_url, :size => "150x150" %>
<%end%>
<% end%>
</div>